openapi: 3.0.0
servers: []
info:
  version: "will-be-set-during-build"
  title: Organizations data definitions
  description: Object definitions for the Organizations on the Winding Tree platform.
paths: {}
components:
  schemas:
    # Off chain data formats
    OrganizationDataIndex:
      title: Organization data index
      description: Landing document for Organization. Link to this document is stored in the Segment Directory record.
      type: object
      required:
      - dataFormatVersion
      - legalEntity
      - updatedAt
      properties:
        dataFormatVersion:
          description: Version number indicating the data format specification version.
          type: string
          format: semver
          maxLength: 20
        name:
          allOf:
            - $ref: '@windingtree/wt-shared-schemas/swagger.yaml#/components/schemas/NameType'
            - description: Human readable name of the Organization that can be used for quick identification.
        legalEntity:
          allOf:
            - oneOf:
              - $ref: '@windingtree/wt-shared-schemas/swagger.yaml#/components/schemas/LegalEntityType'
              - $ref: '@windingtree/wt-shared-schemas/swagger.yaml#/components/schemas/RelationshipSignatureType'
            - description: |
                Legal information about this organization. Either stored directly or as a signed
                relationship reference to another Organization smart contract. Users must verify that the 
                relationship signature is valid (it did not expire and the signature was produced by someone
                associated with the organization, typically a `delegate`).
        updatedAt:
          description: Date-time when the data was last changed. Possibly used by consumers to handle incremental updates and caching.
          type: string
          format: date-time
        guarantee:
          allOf:
            - $ref: '@windingtree/wt-shared-schemas/swagger.yaml#/components/schemas/RelationshipSignatureType'
            - description: |
                *Some other Organization* is guaranteeing that **this Organization** can be trusted. That means
                that when a user is evaluating trustworthiness of **this Organization**, she should take into
                account the trustworthiness of *Some other Organization*.
        hotel:
          $ref: '#/components/schemas/ApiReference'
        airline:
          $ref: '#/components/schemas/ApiReference'
        ota:
          $ref: '#/components/schemas/ApiReference'
    ApiReference:
      title: API reference
      type: object
      required:
        - entrypoint
        - docs
        - type
      properties:
        entrypoint:
          $ref: '@windingtree/wt-shared-schemas/swagger.yaml#/components/schemas/UriType'
        docs:
          $ref: '@windingtree/wt-shared-schemas/swagger.yaml#/components/schemas/UriType'
        type:
          type: string
          enum:
            - windingtree
            - ota
            - htng
            - ndc
            - custom

